// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHvOi_jCgk8D3M_1dapYiJKTcztPOQbT4',
    appId: '1:900392579341:web:9313266cc51c5fdd36c044',
    messagingSenderId: '900392579341',
    projectId: 'flutter-cicd-25a50',
    authDomain: 'flutter-cicd-25a50.firebaseapp.com',
    storageBucket: 'flutter-cicd-25a50.firebasestorage.app',
    measurementId: 'G-3CQF1J813N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtbblIycVBgtIEA6CQ_ujcESwvB_3muOM',
    appId: '1:900392579341:android:9f143784a8e32f0b36c044',
    messagingSenderId: '900392579341',
    projectId: 'flutter-cicd-25a50',
    storageBucket: 'flutter-cicd-25a50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDohSA64WqVI5u83B_k-wijAAaPl5FPKcI',
    appId: '1:900392579341:ios:f8526484ca606aea36c044',
    messagingSenderId: '900392579341',
    projectId: 'flutter-cicd-25a50',
    storageBucket: 'flutter-cicd-25a50.firebasestorage.app',
    iosBundleId: 'com.example.flutterCicd',
  );
}
