require 'dotenv'
Dotenv.load


default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter pub get"
    sh "flutter build apk --release"
    sh "dir build/app/outputs/flutter-apk"
    firebase_app_distribution(
      app: ENV[APP_ID],
      firebase_cli_token: ENV[FIREBASE_CLI_TOKEN],
      android_artifact_type:"APK",
      android_artifact_path: "build/app/outputs/flutter-apk/app-release.apk",
      testers: "mariamattef656@gmail.com,mariamattef2024@gmail.com",
      release_notes: "First Fastlane Firebase App Distribution release"
  )
  end

 
end